name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    environment: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: registry.joncour.xyz
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            registry.joncour.xyz/chatthread:latest
            rregistry.joncour.xyz/chatthread:${{ steps.vars.outputs.sha_short }}
          build-args: |
            "REACT_APP_TWITCH_CLIENTID=${{ secrets.REACT_APP_TWITCH_CLIENTID }}"
            "REACT_APP_TWITCH_CLIENTSECRET=${{ secrets.REACT_APP_TWITCH_CLIENTSECRET }}"
            "REACT_APP_TTS=${{ secrets.REACT_APP_TTS }}"
